name: 'Apply latest configuration profiles via Fleet'
description: 'Applies the latest MDM configuration profiles to a Fleet team'

inputs:
  FLEET_API_TOKEN:
    description: 'Fleet API Token'
    required: true
  FLEET_URL:
    description: 'Fleet URL'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.MDM_CONFIG_REPO }}

    - name: Install fleetctl
      run: npm install -g fleetctl
      shell: bash

    - name: Configure fleetctl
      run: fleetctl config set --address ${{ inputs.FLEET_URL }} --token ${{ inputs.FLEET_API_TOKEN }}
      shell: bash

    - name: Run fleetctl apply
      run: |
        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        # STEP 1: Apply .controls.yml files:
        # (Note that .controls.yml must be applied BEFORE .settings.yml to avoid resetting certain config to the defaults)
        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        # Apply no-team.controls.yml
        # TODO

        # Loop through folders in /teams and apply <folder-name>.controls.yml for each
        # TODO

        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        # STEP 2: Apply .settings.yml files:
        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        # Apply default.settings.yml
        # TODO
        
        # Loop through folders in /teams and apply <folder-name>.settings.yml for each
        # TODO

        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        # STEP 3: Apply queries
        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        # Compile all queries into a single YAML document
        
        # TODO
        # - Add contents of default.queries.yml
        # TODO
        
        # - Loop through folders in /teams and add the contents of <folder-name>.queries.yml for each
        # TODO
        
        # Apply compiled queries YAML with `--replace` (deletes any queries in Fleet that aren't present in this config)
        # TODO

        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        # STEP 4: Apply policies
        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        # Compile all policies into a single YAML document
        # TODO
        
        # - Add contents of default.policies.yml
        # TODO
        
        # - Loop through folders in /teams and add the contents of <folder-name>.policies.yml for each
        # TODO
        
        # Apply compiled policies YAML with `--replace` (deletes any policies in Fleet that aren't present in this config)
        # TODO

        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        # All done!
        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

      shell: bash
