controls: # Controls added to "No team"
  os_updates: # Applies to Fleet Premium only
    macos:
      deadline: "2023-08-11"
      minimum_version: "13.5"
    windows:
      deadline: ""
      grace_period: ""
  os_settings:
    disk_encryption: true # Applies to Fleet Premium only
    custom_settings:
    - ../lib/macos-os-updates.ddm.json
    - ../lib/macos-password.mobileconfig
    - ../lib/windows-screenlock.xml
  setup_experience: # Applies to Fleet Premium only
  scripts:
  - ../lib/collect-fleetd-logs.sh
queries: # Queries added to all teams
- ./lib/collect-fleetd-update-channel.queries.yml
policies: # Policies added to all teams
agent_options: ./lib/agent-options.yml
org_settings:
  server_settings:
    debug_host_ids:
      - 1
      - 3
    enable_analytics: true
    live_query_disabled: false
    query_reports_disabled: false
    scripts_disabled: false
    server_url: https://dogfood.fleetdm.com
  org_info:
    contact_url: https://fleetdm.com/company/contact
    org_logo_url: ""
    org_logo_url_light_background: ""
    org_name: Fleet Device Management
  smtp_settings:
  sso_settings:
    enable_jit_provisioning: true
    enable_jit_role_sync: false
    enable_sso: true
    enable_sso_idp_login: false
    idp_name: Google Workspace
    entity_id: dogfood.fleetdm.com
    metadata: $FLEET_SSO_METADATA
  integrations:
  mdm:
    apple_bm_default_team: Workstations
  webhook_settings:
    vulnerabilities_webhook:
      enable_vulnerabilities_webhook: true
      destination_url: https://example.tines.com/webhook
  fleet_desktop: # Applies to Fleet Premium only
    transparency_url: https://fleetdm.com/transparency
  host_expiry_settings: # Applies to all teams
    host_expiry_enabled: false
  features: # Features added to all teams