# References to shared queries that run on all hosts
---
apiVersion: v1
kind: config
spec:
  queries:
  - ./queries/collect-fleetd-info.queries.yml
  - ./queries/inventory.queries.yml

# One-off queries that run on all hosts
---
apiVersion: v1
kind: query
spec:
  name: osquery_info
  description: A heartbeat counter that reports general performance (CPU, memory) and version.
  query: select i.*, p.resident_size, p.user_time, p.system_time, time.minutes as counter from osquery_info i, processes p, time where p.pid = i.pid;
  interval: 3600 # 1 hour
  observer_can_run: true