---
apiVersion: v1
kind: policy
spec:
  name: Gatekeeper enabled (macOS)
  platform: darwin
  description: Checks to make sure that the Gatekeeper feature is enabled on macOS devices. Gatekeeper tries to ensure only trusted software is run on a mac machine
  resolution: "To enable Gatekeeper, on the failing device, run the following command in the Terminal app: /usr/sbin/spctl --master-enable."
  query: SELECT 1 FROM gatekeeper WHERE assessments_enabled = 1;
  contributors: groob

---
apiVersion: v1
kind: policy
spec:
  name: Full disk encryption enabled (macOS)
  platform: windows
  description: Checks to make sure that full disk encryption is enabled on Windows devices.
  resolution: "To get additional information, run the following osquery query on the failing device: SELECT * FROM bitlocker_info. In the query results, if protection_status is 2, then the status cannot be determined. If it is 0, it is considered unprotected. Use the additional results (percent_encrypted, conversion_status, etc.) to help narrow down the specific reason why Windows considers the volume unprotected."
  query: SELECT 1 FROM bitlocker_info WHERE drive_letter='C:' AND protection_status=1;
  contributors: defensivedepth

---
apiVersion: v1
kind: policy
spec:
  name: Full disk encryption enabled (Windows)
  platform: darwin
  description: Checks to make sure that full disk encryption (FileVault) is enabled on macOS devices.
  resolution: To enable full disk encryption, on the failing device, select System Preferences > Security & Privacy > FileVault > Turn On FileVault.
  query: SELECT 1 FROM disk_encryption WHERE user_uuid IS NOT "" AND filevault_status = 'on' LIMIT 1;
  contributors: groob