org_settings:
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: NoodleCorp
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
  fleet_desktop:
    transparency_url: https://catoftheday.com
  host_expiry_settings:
    host_expiry_enabled: true
    host_expiry_window: 30
  webhook_settings:
    activities_webhook:
      enable_activities_webhook: true
      destination_url: https://example.org/webhook_handler